### ISSUE TITLE
Import into AndBible (Bible+) 

### ISSUE THREAD

**Issue by NotSoImportant** [jd-s/StrongsDicGerman#1]
Hi, how can this be imported into AndBible (now Bible+) on Android? When I open the "import from zip" it seems not to recognize this zip as a valid module.
Or is this anyhow not intendet to work?

**Comment by jd-s** [comment]
SInce this module is not yet in the official repositories, this is the only way to add the module. It worked for me with Version 3.3.399. Which version are you using? What kind of error message do you get?

**Comment by NotSoImportant** [comment]
Hey, now I was able to import it using GhostCommander. When opening in my default file explorer it was shown grayed out.
Thank you. Is really great!
Do you know where I can find the same for the Hebrew Old Testament?

**Comment by NotSoImportant** [comment]
By the way: I found this repo by this German article: https://luki.org/2020/11/quelloffene-bibelsoftware-2-freie-und-offene-formate-fuer-theologische-inhalte-und-bibeln/

**Comment by jd-s** [comment]
There are no Strongs resources for German<->Hebrew as far as I know. I have started a beginning at https://github.com/jd-s/StrongsDicGermanHebrew - but it is far from being finished.

**Comment by bgermann** [comment]
There are no FREELY available/redistributable German<->Hebrew Strongs resources. There are some however at http://www.bibelkommentare.de or at https://clv.de/CLeVer-Erweitertes-Strong-Lexikon/256706

**Comment by jd-s** [comment]
Sorry, but a simple enumeration of translations is not really a dictionary. I created that automatically from the German Translations available in SWORD, but it is not useful. Since Clever is not compatible with SWORD (and I doubt CLV is interested in providing SWORD-modules), this is also not very helpful.

As I said, I have started to work on the Hebrew Dictionary. It is initially an automated translation from the English Dictionary, and I am working through the words one by one. Help is welcome.
